    version: "3"

    services:
        web:
            image: httpd
            container_name: tutorial_1
            ports:
                - 80:80
            volumes:
                - ./src:/usr/local/apache2/htdocs